#!/bin/bash

#Отключаем то, что может нам мешать
setenforce 0
systemctl stop firewalld
 
#Устанавливаем DOCKER и APACHE
yum install yum-utils -y
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install docker-ce docker-ce-cli containerd.io httpd -y
systemctl enable docker
systemctl start docker

#Настраиваем файл /etc/httpd/conf/httpd.conf
sed -i /"Listen 80"$/s/^/#/ /etc/httpd/conf/httpd.conf
sed -i '/#Listen 80/a Listen 8081\nListen 8082\nListen 8083' /etc/httpd/conf/httpd.conf

#Создаем конфиги, директории и файлы для апача
mkdir /var/www/node0{1..3}
echo -e '<VirtualHost *:8081> \n ServerAdmin web@master.local \n DocumentRoot /var/www/node01 \n</VirtualHost>' > /etc/httpd/conf.d/node01.conf
echo -e '<!DOCTYPE HTML><html><head><title>Apache node01</title></head><body><H1>\nApache node01 work!!!\n</H1></body></html>' > /var/www/node01/index.html

echo -e '<VirtualHost *:8082> \n ServerAdmin web@master.local \n DocumentRoot /var/www/node02 \n</VirtualHost>' > /etc/httpd/conf.d/node02.conf
echo -e '<!DOCTYPE HTML><html><head><title>Apache node02</title></head><body><H1>\nApache node02 work!!!\n</H1></body></html>' > /var/www/node02/index.html

echo -e '<VirtualHost *:8083> \n ServerAdmin web@master.local \n DocumentRoot /var/www/node03 \n</VirtualHost>' > /etc/httpd/conf.d/node03.conf
echo -e '<!DOCTYPE HTML><html><head><title>Apache node03</title></head><body><H1>\nApache node03 work!!!\n</H1></body></html>' > /var/www/node03/index.html

#Запускаем nginx
docker run -it -d -p 80:80 --name web nginx
