#!/bin/bash

#Отключаем то, что может нам мешать
setenforce 0
systemctl stop firewalld

#Устанавливаем нажное ПО
yum install wget -y

#добавляем служебных пользователей для службы мониторинга
useradd -M -s /usr/sbin/nologin prometheus
useradd -M -s /usr/sbin/nologin node_exporter

#Создаем необходимые каталоги и даем соответсвующие права
mkdir /etc/prometheus /var/lib/prometheus
chown prometheus:prometheus /etc/prometheus /var/lib/prometheus

#Устанавливаем prometheus и node exporter
mkdir prometheus
cd ./prometheus
wget --no-check-certificate https://github.com/prometheus/prometheus/releases/download/v2.26.0/prometheus-2.26.0.linux-amd64.tar.gz
wget --no-check-certificate https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz
tar -xzf prometheus-2.26.0.linux-amd64.tar.gz
tar -xzf node_exporter-1.1.2.linux-amd64.tar.gz

cp ./node_exporter-1.1.2.linux-amd64/node_exporter /usr/local/bin/
cp ./prometheus-2.26.0.linux-amd64/prometheus /usr/local/bin/
cp ./prometheus-2.26.0.linux-amd64/promtool /usr/local/bin/

chown node_exporter:node_exporter /usr/local/bin/node_exporter
chown prometheus:prometheus /usr/local/bin/prometheus
chown prometheus:prometheus /usr/local/bin/promtool

cd ./prometheus-2.26.0.linux-amd64/
cp -r ./console_libraries /etc/prometheus
cp -r ./consoles /etc/prometheus
cp ./prometheus.yml /etc/prometheus
cd ..

chown -R prometheus:prometheus /etc/prometheus

echo "[Unit] 
Description=Node Exporter
Wants=network-online.target
After=network-online.target

[Service]
User=node_exporter
Group=node_exporter
Type=simple
ExecStart=/usr/local/bin/node_exporter

[Install]
WantedBy=multi-user.target" > /etc/systemd/system/node_exporter.service

echo "[Unit]
Description=Prometheus Monitoring
Wants=network-online.target
After=network-online.target

[Service]
User=prometheus
Group=prometheus
Type=simple
ExecStart=/usr/local/bin/prometheus \
--config.file /etc/prometheus/prometheus.yml \
--storage.tsdb.path /var/lib/prometheus/ \
--web.console.templates=/etc/prometheus/consoles \
--web.console.libraries=/etc/prometheus/console_libraries
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target" > /etc/systemd/system/prometheus.service

echo "
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9100']
" >> /etc/prometheus/prometheus.yml

systemctl start prometheus node_exporter

#Устанавливаем grafana
wget https://dl.grafana.com/oss/release/grafana-7.5.5-1.x86_64.rpm
yum install -y ./grafana-7.5.5-1.x86_64.rpm
systemctl daemon-reload
systemctl start grafana-server
