#!/bin/bash

#Отключаем то, что может нам мешать
setenforce 0
systemctl stop firewalld

#Устанавливаем mysql
curl -O https://repo.mysql.com//mysql80-community-release-el7-3.noarch.rpm
rpm -Uvh mysql80-community-release-el7-3.noarch.rpm
rm mysql80-community-release-el7-3.noarch.rpm -f
yum install mysql-server expect -y
systemctl enable mysqld
systemctl start mysqld

#Вытаскиваем временный пароль от MySQL
MYSQL_TMP_PASS=$(grep 'temporary password' /var/log/mysqld.log | grep -oE '[^ ]+$')
MYSQL_PASS='Qq123456!'
echo $MYSQL_TMP_PASS
