#!/bin/bash

#Отключаем то, что может нам мешать
setenforce 0
systemctl stop firewalld

#Устанавливаем mysql
curl -O https://repo.mysql.com//mysql80-community-release-el7-3.noarch.rpm
rpm -Uvh mysql80-community-release-el7-3.noarch.rpm
rm mysql80-community-release-el7-3.noarch.rpm -f
yum install mysql-server expect -y
systemctl enable mysqld
systemctl start mysqld

#Вытаскиваем временный пароль от MySQL
MYSQL_TMP_PASS=$(grep 'temporary password' /var/log/mysqld.log | grep -oE '[^ ]+$')
MYSQL_PASS='Qq123456!'

script=<<'SCRIPT_END'
set timeout -1
spawn mysql_secure_installation
match_max 100000
expect -exact \"\r
\r

Enter password for user root: \"
send -- \"$MYSQL_TMP_PASS\r\"
expect -exact \"\r
\r

Change the password for root ? ((Press y|Y for Yes, any other key for No) : \"
send -- \"y\r\"
expect -exact \"y\r
\r

New password: \"
send -- \"$MYSQL_PASS\r\"
expect -exact \"\r
\r

Re-enter new password: \"
send -- \"$MYSQL_PASS\r\"
expect -exact \"\r
\r

Estimated strength of the password: 100 \r
Do you wish to continue with the password provided?(Press y|Y for Yes, any other key for No) : \"
send -- \"y\r\"
expect -exact \"y\r
\r

Remove anonymous users? (Press y|Y for Yes, any other key for No) : \"
send -- \"y\r\"
expect -exact \"y\r
Success.\r
\r

Disallow root login remotely? (Press y|Y for Yes, any other key for No) : \"
send -- \"y\r\"
expect -exact \"y\r
\r

Remove test database and access to it? (Press y|Y for Yes, any other key for No) : \"
send -- \"y\r\"
expect -exact \"y\r
\r

Reload privilege tables now? (Press y|Y for Yes, any other key for No) : \"
send -- \"y\r\"
interact
SCRIPT_END

VAR=$(expect -c "$script")
echo "$VAR"
