#!/bin/bash
#Настройка SLAVE сервера

#Отключаем то, что может нам мешать
setenforce 0
systemctl stop firewalld

#Устанавливаем переменные
#MYSQL_PASS - новый пароль от MySQL
#MASTER_SRV_IP - IP адрес MASTER сервера
#SLAVE_SRV_IP - IP адрес SLAVE сервера
MYSQL_PASS='Qq123456!'
MASTER_SRV_IP='192.168.10.22';
SLAVE_SRV_IP='192.168.10.23';

#Устанавливаем mysql
curl -O https://repo.mysql.com//mysql80-community-release-el7-3.noarch.rpm
rpm -Uvh mysql80-community-release-el7-3.noarch.rpm
rm mysql80-community-release-el7-3.noarch.rpm -f
yum install mysql-server expect -y
echo 'server_id = 2' >> /etc/my.cnf
systemctl enable mysqld
systemctl start mysqld

#Вытаскиваем временный пароль от MySQL
MYSQL_TMP_PASS=$(grep 'temporary password' /var/log/mysqld.log | grep -oE '[^ ]+$')

echo $MYSQL_TMP_PASS

#Автомтизируем mysql_secure_installation
/usr/bin/expect<<EXP_SCRIPT

set timeout 10
spawn mysql_secure_installation
match_max 100000
expect -exact "Enter password for user root: "
send -- "$MYSQL_TMP_PASS\r"
expect -exact "New password: "
send -- "$MYSQL_PASS\r"
expect -exact "Re-enter new password: "
send -- "$MYSQL_PASS\r"
expect -exact "Change the password for root ? ((Press y|Y for Yes, any other key for No) : "
send -- "n\r"
expect -exact "Remove anonymous users? (Press y|Y for Yes, any other key for No) : "
send -- "y\r"
expect -exact "Disallow root login remotely? (Press y|Y for Yes, any other key for No) : "
send -- "y\r"
expect -exact "Remove test database and access to it? (Press y|Y for Yes, any other key for No) : "
send -- "y\r"
expect -exact "Reload privilege tables now? (Press y|Y for Yes, any other key for No) : "
send -- "y\r"
expect eof

EXP_SCRIPT


mysql -u 'usr_slave' -h $MASTER_SRV_IP -p$MYSQL_PASS -e "SHOW MASTER STATUS\G;" | grep File | grep -oE '[^ ]+$'
