#!/bin/bash

echo 'TYPE="Ethernet"
PROXY_METHOD="none"
BROWSER_ONLY="no"
BOOTPROTO="static"
IPADDR="192.168.10.22"
NETMASK="255.255.255.0"
GATEWAY="192.168.10.1"
DNS1="8.8.8.8"
DNS2="8.8.4.4"
DEFROUTE="yes"
IPV4_FAILURE_FATAL="no"
IPV6INIT="yes"
IPV6_AUTOCONF="yes"
IPV6_DEFROUTE="yes"
IPV6_FAILURE_FATAL="no"
IPV6_ADDR_GEN_MODE="stable-privacy"
NAME="enp0s3"
UUID="673f43db-a34c-4f66-87c3-89356a78d5ac"
DEVICE="enp0s3"
ONBOOT="yes"' > /etc/sysconfig/network-scripts/ifcfg-enp0s3

systemctl restart network
