#!/bin/bash

#устанавливаем все службы
yum install epel-release -y
yum install httpd nginx -y

#включаем автозапуск служб
systemctl enable httpd nginx

#разрешаем на фаирволе нужные порты
firewall-cmd --zone=public --permanent --add-service=http
firewall-cmd --reload

#Настраиваем файл /etc/httpd/conf/httpd.conf
sed -i /"Listen 80"$/s/^/#/ /etc/httpd/conf/httpd.conf
sed -i '/#Listen 80/a Listen 8081\nListen 8082\nListen 8083' /etc/httpd/conf/httpd.conf

#Создаем конфиги, директории и файлы для апача
mkdir /var/www/node0{1..3}
echo -e '<VirtualHost *:8081> \n ServerAdmin web@master.local \n DocumentRoot /var/www/node01 \n</VirtualHost>' > /etc/httpd/conf.d/node01.conf
echo -e '<!DOCTYPE HTML><html><head><title>Apache node01</title></head><body><H1>\nApache node01 work!!!\n</H1></body></html>' > /var/www/node01/index.html

echo -e '<VirtualHost *:8082> \n ServerAdmin web@master.local \n DocumentRoot /var/www/node02 \n</VirtualHost>' > /etc/httpd/conf.d/node02.conf
echo -e '<!DOCTYPE HTML><html><head><title>Apache node02</title></head><body><H1>\nApache node02 work!!!\n</H1></body></html>' > /var/www/node02/index.html

echo -e '<VirtualHost *:8083> \n ServerAdmin web@master.local \n DocumentRoot /var/www/node03 \n</VirtualHost>' > /etc/httpd/conf.d/node03.conf
echo -e '<!DOCTYPE HTML><html><head><title>Apache node03</title></head><body><H1>\nApache node03 work!!!\n</H1></body></html>' > /var/www/node03/index.html

#Конфигурируем файл балансировки и прописываем в конфиг нджинкса
echo -e 'upstream httpd-test {\nserver localhost:8081;\nserver localhost:8082;\nserver localhost:8083;\n}' > /etc/nginx/conf.d/upstream.conf
sed -i '/location \x2F \x7B/a proxy_pass http\x3A\x2F\x2Fhttpd-test\x2F\x3B' /etc/nginx/nginx.conf

#запускаем службы апача и нджинкса
systemctl start httpd nginx

#Проверяем работу нод апача
curl localhost | grep work
curl localhost | grep work
curl localhost | grep work
